catalog/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^books/$', views.BookListView.as_view(), name='books'),
        url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
        url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
        url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [   
    url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

urlpatterns += [   
    url(r'^author/create/$', views.AuthorCreate.as_view(), name='author_create'),
    url(r'^author/(?P<pk>\d+)/update$', views.AuthorUpdate.as_view(), name='author_update'),
    url(r'^author/(?P<pk>\d+)/delete$', views.AuthorDelete.as_view(), name='author_delete'),
]

urlpatterns += [   
    url(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    url(r'^book/(?P<pk>\d+)/update$', views.BookUpdate.as_view(), name='book_update'),
    url(r'^book/(?P<pk>\d+)/delete$', views.BookDelete.as_view(), name='book_delete'),
]

urlpatterns += [   
    url(r'^boutiques/$', views.BoutiqueListView.as_view(), name='boutiques'),
    url(r'^boutique/(?P<pk>\d+)$', views.BoutiqueDetailView.as_view(), name='boutique-detail'),
    url(r'^boutique/create/$', views.BoutiqueCreate.as_view(), name='boutique_create'),
    url(r'^boutique/(?P<pk>\d+)/update$', views.BoutiqueUpdate.as_view(), name='boutique_update'),
    url(r'^boutique/(?P<pk>\d+)/delete$', views.BoutiqueDelete.as_view(), name='boutique_delete'),
]


urlpatterns += [
    url(r'^register/$', views.register, name='register'),
    url(r'user/$', views.user, name='user'),
    url(r'^user/(?P<pk>\d+)/update$', views.UserUpdate.as_view(), name='user_update'),
    url(r'search/$', views.search, name='search'),
]

urlpatterns += [
        url(r'^cart/$', views.CartView.as_view(), name='cart'),
        url(r'^comparaison/$', views.comparaison, name='comparaison'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path(r'accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
from django.core.files.storage import FileSystemStorage
from django.conf import settings

import uuid

image_storage = FileSystemStorage(
        location=u'{0}/'.format(settings.MEDIA_ROOT), 
        base_url=u'{0}/'.format(settings.MEDIA_URL),
        )

def image_directory_path(instance, filename):
    return u'{0}'.format(filename)

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a book genre.")
    def __str__(self):
        return self.name
    
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    photo = models.ImageField(upload_to="media/images/", null=True, blank=True)
    quantity = models.DecimalField(max_digits=5, decimal_places=0, default=0)
    
    def __str__(self):
        return self.title
    
    def get_title(self):
        return "%s" %(self.title)

    def remove_from_cart(self):
        return "%s?ItemID=%s&qty=1&DeleteItem=True" %(reverse("cart"), self.id)
    
    def get_quantity(self):
        return self.quantity
    
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
    
    class Meta : 
        ordering = ["title"]
    
    def display_genre(self):
        return ', '.join([genre.name for genre in self.genre.all()[:3]])
    display_genre.short_description = 'Genre'
    
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')
    
    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)
        
    def __str__(self):
        return '%s (%s)' % (self.id,self.book.title)

    
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    image = models.ImageField(upload_to="media/images/autheur", null=True)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)
    
    def get_books_count(self):
        return Book.objects.filter(author=self).count()
    
    def get_books_from_author(self):
        return Book.objects.filter(author=self)

    class Meta:
        ordering = ['last_name']
        
class Boutique(models.Model):
    name = models.CharField(max_length=100)
    open_year = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to="media/images/boutiques", null=True, blank=True)
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=5)
    book = models.ManyToManyField('Book', blank=True) 
    
    def get_absolute_url(self):
        return reverse('boutique-detail', args=[str(self.id)])

    def __str__(self):
        return '%s, %s' % (self.id, self.name)

    class Meta:
        ordering = ['name']
        
@property
def is_overdue(self):
    if self.due_back and date.today() > self.due_back:
        return True
    return False

class Panier(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    items = models.ManyToManyField(Book, through = 'PanierItem')
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    def __str__(self):
        return str(self.id)
        
class PanierItem(models.Model):
    cart = models.ForeignKey(Panier, on_delete=models.CASCADE)
    item = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=5, decimal_places=0, default=1)
    
    def __str__(self):
        return self.item.title
    
    def remove(self):
                return self.item.remove_from_cart()

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.base import View
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm, User

from .models import Book, Author, BookInstance, Boutique, Panier, PanierItem
from tkinter import messagebox

def register(request):
    if request.method == 'POST':
        f = UserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            reverse_lazy('books')
    else:
        f = UserCreationForm()

    return render(request, 'catalog/register.html', {'form': f})

def user(request):
    return render(
        request,
        'catalog/user_detail.html',
        {'cart':Panier.objects.all()}
    )

def index(request):
    # Generate counts of some of the main objects
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    # Available books (status = 'a')
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()  # The 'all()' is implied by default.
    num_shops=Boutique.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    
    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_books':num_books,
                 'num_instances':num_instances,
                 'num_instances_available':num_instances_available,
                 'num_authors':num_authors, 
                 'num_visits':num_visits, 
                 'num_shops':num_shops,
                 'boutique':Boutique.objects.all(),
                 'book': Book.objects.all(),
                 'author': Author.objects.all(),
                }
    )
    
    
class BookListView(generic.ListView):
    model = Book    
    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['some_data'] = 'This is just some data'
        return context
    
    def get_queryset(self):
        query = self.request.GET.get('q')
        page = self.request.GET.get('page')
        if query :
            return Book.objects.filter(title__icontains=query)
        elif page:
            return Book.objects.filter(title__startswith=page)
        else:
            return Book.objects.all()
    
class BookDetailView(generic.DetailView):
    model = Book
    
def book_detail_view(request,pk):    
    try:
        book_id=Book.objects.get(pk=pk)
    except Book.DoesNotExist:
        raise Http404("Book does not exist")
        
    return render(
        request,
        'catalog/book_detail.html',
        context={'book':book_id,}
    )
    
class BoutiqueListView(generic.ListView):
    model = Boutique
    def get_context_data(self, **kwargs):
        context = super(BoutiqueListView, self).get_context_data(**kwargs)
        context['some_data'] = 'This is just some data'
        return context
    
    def get_queryset(self):
        query = self.request.GET.get('q')        
        page = self.request.GET.get('page')
        if query :
            return Boutique.objects.filter(name__icontains=query)
        elif page:
            return Boutique.objects.filter(name__startswith=page)
        else:
            return Boutique.objects.all()
        
class BoutiqueDetailView(generic.DetailView):
    model = Boutique
    
def boutique_detail_view(request,pk):    
    try:
        boutique_id=Boutique.objects.get(pk=pk)
    except Boutique.DoesNotExist:
        raise Http404("Book does not exist")
        
    return render(
        request,
        'catalog/boutique_detail.html',
        context={'boutique':boutique_id,}
    )

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
    
class AuthorListView(generic.ListView):
    model = Author
    def get_context_data(self, **kwargs):
        context = super(AuthorListView, self).get_context_data(**kwargs)
        context['some_data'] = 'This is just some data'
        return context
    
    def get_queryset(self):
        query = self.request.GET.get('q')
        page = self.request.GET.get('page')
        if query :
            return Author.objects.filter(first_name__icontains=query)
        elif page:
            return Author.objects.filter(first_name__startswith=page)
        else:
            return Author.objects.all()

class AuthorDetailView(generic.DetailView):
    model = Author
    
def author_detail_view(request,pk):
    try:
        author_id=Author.objects.get(pk=pk)
        book = Book.objects.all()
    except Author.DoesNotExist:
        raise Http404("Author does not exist")
    
    return render(
        request,
        'catalog/author_detail.html',
        context={'author':author_id,
                 'book': book}
    )
    
########Creating view to manage User informations#########
class UserUpdate(UpdateView):
    model = User
    fields =['username', 'first_name','last_name', 'email']
    template_name = 'catalog/user_form.html'
    success_url = reverse_lazy('user')
    
    def get_object(self, queryset=None):
        '''This method will load the object
           that will be used to load the form
           that will be edited'''
        return self.request.user

########Creating view to manage Authors#########
class AuthorCreate(CreateView) :
    model = Author
    fields = '__all__'
    initial = {'date_of_death':'12/10/2016', 'date_of_birth':'12/10/2016'} #dateformat = mm/dd/yyyy
    
class AuthorUpdate(UpdateView) :
    model = Author
    fields = ['first_name','last_name','date_of_birth','date_of_death']
    
class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

########Creating view to manage Books#########
class BookCreate(CreateView) :
    model = Book
    fields = '__all__'
    
class BookUpdate(UpdateView) :
    model = Book
    fields = ['Title','Author','Summary','ISBN','Genre']
    
class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    
########Creating view to manage Books#########
class BoutiqueCreate(CreateView) :
    model = Boutique
    fields = '__all__'
    
class BoutiqueUpdate(UpdateView) :
    model = Boutique
    
class BoutiqueDelete(DeleteView):
    model = Boutique
    success_url = reverse_lazy('boutiques')

def search(request):
    return render(request, 'catalog/search.html', context = {
                    'book' : Book.objects.filter(title__icontains=request.GET.get('q')), 
                    'author' : Author.objects.filter(first_name__icontains=request.GET.get('q')),
                    'boutique' : Boutique.objects.filter(name__icontains=request.GET.get('q'))
                    })

########Customer Cart functions#########
class CartView(View):
        model = Panier
        template_name = "catalog/panier.html"
        
        def get(self, request):
                self.request.session.set_expiry(0) #till browser closed

                cart_id = self.request.session.get("catalogID") #you can use any name "cartID"

                #if no session exist, create new and save
                if cart_id == None:
                    cart = Panier()
                    cart.save()
    
                    #save cart_id for first use.
                    cart_id = cart.id # After this it will save by line 18
                    self.request.session["catalogID"] = cart.id #save session
    
                # save current cartID into cart,
                # for displaying cart item in template
                cart = Panier.objects.get(id=cart_id)

                #if already login, save username in Cart
                if self.request.user.is_authenticated == True:
                        cart.user = self.request.user
                        cart.save()

                #ItemID is coming from book_detail.html
                #get it to add the item in current session.
                item_id = request.GET.get("ItemID")
                
                # get the book with format from above ID
                item_instance = get_object_or_404(Book, id=item_id)

                #save the above book in cart item
                cart_item, created = PanierItem.objects.get_or_create(cart=cart, item=item_instance)
                
                item_qty = request.GET.get("qty")
                
                #get DeleteItem from url, defined in Format class
                delete_item = request.GET.get("DeleteItem")
        
                if int(item_qty) < 1:
                        delete_item = True
                    
                #both delete and qty appear on link, if DeleteItem exist then delete it,
                #otherwise set the correct quntity.
                if delete_item:
                    cart_item.delete()
                else:
                    cart_item.quantity = item_qty
                    cart_item.save()
                        
                context = {
                        "cart": cart,
                        "qty": item_qty,
                }
                template = self.template_name
                return render(request, template, context)
            
########Compison function#########
def comparaison(request):
    template = "catalog/comparaison.html"
    
    comp1= "No book_id value in the form submited..."
    comp2= "No book_id value in the form submited..."
    comp3= "No book_id value in the form submited..."

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Delete Author</h1>

    <p>Are you sure you want to delete the author: {{ author }}?</p>

    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" action="" value="Yes, delete." />
    </form>

{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}

    <form action="" method="post"  enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <div>
        <h1>Author List ({{author_list|length}})</h1>
        
        <ul class="pagination">
            <li class="disabled"><a href="?page={{boutique.previous_page}}"><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="?page=A">A</a></li>
            <li class="waves-effect"><a href="?page=B">B</a></li>
            <li class="waves-effect"><a href="?page=C">C</a></li>
            <li class="waves-effect"><a href="?page=D">D</a></li>
            <li class="waves-effect"><a href="?page=E">E</a></li>
            <li class="waves-effect"><a href="?page=F">F</a></li>
            <li class="waves-effect"><a href="?page=G">G</a></li>
            <li class="waves-effect"><a href="?page=H">H</a></li>
            <li class="waves-effect"><a href="?page=I">I</a></li>
            <li class="waves-effect"><a href="?page=J">J</a></li>
            <li class="waves-effect"><a href="?page=K">K</a></li>
            <li class="waves-effect"><a href="?page=L">L</a></li>
            <li class="waves-effect"><a href="?page=M">M</a></li>
            <li class="waves-effect"><a href="?page=N">N</a></li>
            <li class="waves-effect"><a href="?page=O">O</a></li>
            <li class="waves-effect"><a href="?page=P">P</a></li>
            <li class="waves-effect"><a href="?page=Q">Q</a></li>
            <li class="waves-effect"><a href="?page=R">R</a></li>
            <li class="waves-effect"><a href="?page=S">S</a></li>
            <li class="waves-effect"><a href="?page=T">T</a></li>
            <li class="waves-effect"><a href="?page=U">U</a></li>
            <li class="waves-effect"><a href="?page=V">V</a></li>
            <li class="waves-effect"><a href="?page=W">W</a></li>
            <li class="waves-effect"><a href="?page=X">X</a></li>
            <li class="waves-effect"><a href="?page=Y">Y</a></li>
            <li class="waves-effect"><a href="?page=Z">Z</a></li>
            <li class="waves-effect"><a href="?page={{boutique.next_page}}"><i class="material-icons">chevron_right</i></a></li>
          </ul>
        
        {% if 'user.can_add_author' in perms %}
            <a href="/catalog/author/create" class="btn-floating waves-effect " style="float:right;">
                <i class="material-icons">add</i>
            </a>
        {% endif %}
    </div>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
          {% if 'user.can_delete_author' in perms %}
              <a href="/catalog/author/{{ author.id }}/delete" class="btn-floating waves-effect" style="background-color : rgba(240,10,10,0.7)">
                  <i class="material-icons">delete</i>
              </a>
          {% endif %}
          <a href="/catalog/author/{{ author.id }}">{{ author.first_name }} {{ author.last_name }} ({{ author.date_of_birth }} ~ {{ author.date_of_death }})</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no authors in the library.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  {% if book.photo %}
      <img src="{{book.photo.url}}" width="200" height="200" style="">
  {% endif %}
  <p><strong>Author:</strong> <a href="/catalog/author/{{ book.author.id }}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
  <div class="row ">    
      <div class="col s6">
        <form method="GET" action="{% url 'cart' %}">
            <input type="hidden" name="ItemID" value="{{book.id}}" />
            <p>Quantity <input type="number" name="qty" value="1" /><p>
            <input type="submit" value="Add to Cart" class="btn btn-default" />
        </form>
      </div>
   </div>
{% endblock %}  

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
{% block content %}

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/boutique_detail.html
{% extends "base_generic.html" %}

{% block content %}
  
  <h1>{{ boutique.name }}</h1>
  {% if boutique.open_year %}
      <h10>{{ boutique.open_year }}</h10>
  {%endif%}
   <div>
       <h3>Liste des livres disponibles en boutique ({{boutique.book.count}}) : </h3>
       {% if boutique.book.count > 0 %}
           <table class="striped">
               <thead>
                   <tr>
                       <th>Titre</th>
                       <th>Auteur</th>
                       <th>Genre</th>
                   </tr>
                </thead>
                <tbody>
                    {% for book in boutique.book.all %}
                      <tr>
                        <td><a href="{{book.get_absolute_url}}">{{book.title}}</a></td>
                        <td><a href="/catalog/author/{{book.author.id}}">{{ book.author }}</td>
                        <td>{{book.genre}}</td>
                      </tr>
                    {% endfor %}
                </tbody>
              </table>
       {% else %}
           <p>Pas de livre disponible pour le moment. </p>
       {% endif %}
   <div>
  <div>
      <h3>Adresse 
          {% if boutique.image %}
              <img src="{{boutique.image.url}}" width="120" height="100" >
          {% endif %}
      </h3>
      {{boutique.street}} <br> {{boutique.zip_code}} {{boutique.city}}<br> {{boutique.state}} 
   <div>
   <div id="googleMap" style="width:100%;height:400px;"></div>

    <script type="text/javascript">
        function myMap() {
        
            var latitude = 0.0;
            var longitude = 0.0;
            
            var mapProp= {
                center:new google.maps.LatLng(longitude,latitude),
                zoom:5,
            };
            var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
            
            var geocoder = new google.maps.Geocoder();
            var address = "{{boutique.street}} {{boutique.zip_code}} {{boutique.city}}"
            geocoder.geocode( { address: address}, 
                function(results, status) {
                    if (status.toLowerCase() == 'ok') {
                        var coords = new google.maps.LatLng(
        						results[0]['geometry']['location'].lat(),
        						results[0]['geometry']['location'].lng()
        					);
                        map.setCenter(coords);
                        map.setZoom(18);
        					marker = new google.maps.Marker({
        						position: coords, 
        						map: map, 
        						title: "{{boutique.name}}",
        					});
                    } 
                }); 
            
        }
    </script>
    
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBtTZRBZmF_nrsEAD_FctJM32luMjcEkqI&callback=myMap"></script>

{% endblock %}

catalog/templates/catalog/boutique_form.html
{% extends "base_generic.html" %}

{% block content %}

    <form action="" method="post"  enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

catalog/templates/catalog/boutique_list.html
{% extends "base_generic.html" %}

{% block content %}
    <div>
        <h1>Boutique List ({{boutique_list|length}})</h1>
        
          <ul class="pagination">
            <li class="disabled"><a href="?page={{boutique.previous_page}}"><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="?page=A">A</a></li>
            <li class="waves-effect"><a href="?page=B">B</a></li>
            <li class="waves-effect"><a href="?page=C">C</a></li>
            <li class="waves-effect"><a href="?page=D">D</a></li>
            <li class="waves-effect"><a href="?page=E">E</a></li>
            <li class="waves-effect"><a href="?page=F">F</a></li>
            <li class="waves-effect"><a href="?page=G">G</a></li>
            <li class="waves-effect"><a href="?page=H">H</a></li>
            <li class="waves-effect"><a href="?page=I">I</a></li>
            <li class="waves-effect"><a href="?page=J">J</a></li>
            <li class="waves-effect"><a href="?page=K">K</a></li>
            <li class="waves-effect"><a href="?page=L">L</a></li>
            <li class="waves-effect"><a href="?page=M">M</a></li>
            <li class="waves-effect"><a href="?page=N">N</a></li>
            <li class="waves-effect"><a href="?page=O">O</a></li>
            <li class="waves-effect"><a href="?page=P">P</a></li>
            <li class="waves-effect"><a href="?page=Q">Q</a></li>
            <li class="waves-effect"><a href="?page=R">R</a></li>
            <li class="waves-effect"><a href="?page=S">S</a></li>
            <li class="waves-effect"><a href="?page=T">T</a></li>
            <li class="waves-effect"><a href="?page=U">U</a></li>
            <li class="waves-effect"><a href="?page=V">V</a></li>
            <li class="waves-effect"><a href="?page=W">W</a></li>
            <li class="waves-effect"><a href="?page=X">X</a></li>
            <li class="waves-effect"><a href="?page=Y">Y</a></li>
            <li class="waves-effect"><a href="?page=Z">Z</a></li>
            <li class="waves-effect"><a href="?page={{boutique.next_page}}"><i class="material-icons">chevron_right</i></a></li>
          </ul>
            
        
        {% if 'user.can_add_boutique' in perms %}
            <a href="/catalog/boutique/create" class="btn-floating waves-effect " style="float:right;">
                <i class="material-icons">add</i>
            </a>
        {% endif %}
    </div>

    {% if boutique_list %}
    <ul>

      {% for boutique in boutique_list %}
      <li>
          {% if 'user.can_delete_boutique' in perms %}
              <a href="/catalog/boutique/{{ boutique.id }}/delete" class="btn-floating waves-effect" style="background-color : rgba(240,10,10,0.7)">
                  <i class="material-icons">delete</i>
              </a>
          {% endif %}
          <a href="/catalog/boutique/{{ boutique.id }}">{{ boutique.name }} ({{ boutique.open_year }})</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no boutique references in the library.</p>
    {% endif %}       
{% endblock %}